backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: "src/images";
public_folder: "/images";

collections:
  - name: "gallery" # Used in routes, e.g., /admin/collections/blog
    label: "gallery" # Used in the UI
    folder: "src/gallery" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Gallery Image", name: "gallery-image", widget: "image"}
